# Generated by Django 4.1.2 on 2022-10-31 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BF', 'Baked Foods'), ('SN', 'Snacks'), ('SW', 'Sweets'), ('VG', 'Vegetables'), ('AI', 'American Indian'), ('RF', 'Restaurant Foods'), ('BV', 'Beverages'), ('FO', 'Fats and Oils'), ('ME', 'Meats'), ('DE', 'Dairy and Egg Products'), ('BF', 'Baby Foods'), ('BC', 'Breakfast Cereals'), ('SS', 'Soups and Sauces'), ('BL', 'Beans and Lentils'), ('FI', 'Fish'), ('FR', 'Fruits'), ('GP', 'Grains and Pasta'), ('NS', 'Nuts and Seeds'), ('FF', 'Fast Foods'), ('SH', 'Spices and Herbs'), ('PM', 'Prepared Meals')], max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('age', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('activity', models.DecimalField(decimal_places=3, max_digits=5)),
                ('calories', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyKcal.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
