# Generated by Django 4.1.2 on 2022-10-31 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyKcal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'Sedentary (Office Job, ...)'), ('L', 'Light Exercise (1-3 days/week)'), ('M', 'Moderate Exercise (4-5 days/week)'), ('H', 'Heavy Exercise (6-7 days/week)'), ('A', 'Athlete (2x per day)')], max_length=50)),
                ('score', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyKcal.activity'),
        ),
    ]
