# Generated by Django 4.1.2 on 2022-10-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyKcal', '0002_activity_alter_userprofile_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('BF', 'Baked Foods'), ('SN', 'Snacks'), ('SW', 'Sweets'), ('VG', 'Vegetables'), ('AI', 'American Indian'), ('RF', 'Restaurant Foods'), ('BV', 'Beverages'), ('FO', 'Fats and Oils'), ('ME', 'Meats'), ('DE', 'Dairy and Egg Products'), ('BAF', 'Baby Foods'), ('BC', 'Breakfast Cereals'), ('SS', 'Soups and Sauces'), ('BL', 'Beans and Lentils'), ('FI', 'Fish'), ('FR', 'Fruits'), ('GP', 'Grains and Pasta'), ('NS', 'Nuts and Seeds'), ('FF', 'Fast Foods'), ('SH', 'Spices and Herbs'), ('PM', 'Prepared Meals')], max_length=50),
        ),
    ]
