# Generated by Django 4.1.2 on 2022-10-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyKcal', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(choices=[('Sedentary (Office Job, ...)', 'Sedentary (Office Job, ...)'), ('Light Exercise (1-3 days/week)', 'Light Exercise (1-3 days/week)'), ('Moderate Exercise (4-5 days/week)', 'Moderate Exercise (4-5 days/week)'), ('Heavy Exercise (6-7 days/week)', 'Heavy Exercise (6-7 days/week)'), ('Athlete (2x per day)', 'Athlete (2x per day)')], max_length=50),
        ),
    ]
