# Generated by Django 4.1.2 on 2022-10-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyKcal', '0006_alter_activity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='calories',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
