# Generated by Django 4.1.2 on 2022-10-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyKcal', '0008_remove_userprofile_id_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
